# Generated by Django 4.1 on 2022-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('Tarih', 'Tarih'), ('Bilim', 'Bilim')], default='Tarih', max_length=30, verbose_name='İçerik Türü'),
        ),
    ]
